#!/usr/bin/env python3
"""
Build postcard — 山野通行证风格明信片。
Reads data from route_data.json + build_data.json generated by build_trail_poster.py.
"""
import re, json, math, os
import sys
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
PROJECT_DIR = BASE_DIR.parent
REFERENCES = Path(os.environ.get("SHANYE_REFERENCES_ROOT", BASE_DIR / "references"))
OUTPUT = Path(os.environ.get("SHANYE_OUTPUT_ROOT", BASE_DIR / "output"))
sys.path.insert(0, str(BASE_DIR / "scripts"))
from design_constraints import get_in, load_design_constraints, product_constraints

constraints = load_design_constraints(BASE_DIR)
postcard_constraints = product_constraints(constraints, "postcard")
source_constraints = constraints.get("source", {})
postcard_palette = get_in(postcard_constraints, ["script_hooks", "product_palette"], {})
style_variant = get_in(
    postcard_constraints,
    ["script_hooks", "style_variant"],
    get_in(postcard_constraints, ["script_hooks", "visual_treatment"], "trail_permit_pass"),
)

# === 1. Read route metadata ===
route_data_path = REFERENCES / "route_data.json"
with open(route_data_path, "r", encoding="utf-8") as f:
    route_data = json.load(f)

content_path = REFERENCES / "content_assets.json"
with open(content_path, "r", encoding="utf-8") as f:
    content = json.load(f)

stats = route_data
total_dist_km = stats["total_distance_km"]
elevation_gain = int(stats["elevation_gain"])
max_elev = int(stats["max_elevation"])
route_name = source_constraints.get("route_name", content.get("route_name", "路线纪念"))
route_sub = content.get("route_subtitle", "")
team_name = source_constraints.get("team_name", content.get("team_name", "山野路迹"))

# === 2. Read build_data.json for photo markers (to find hero photo) ===
build_data_path = OUTPUT / "build_data.json"
with open(build_data_path, "r", encoding="utf-8") as f:
    build_data = json.load(f)

PHOTO_MARKERS = build_data["photo_markers"]

# Find hero photo (highest SRTM elevation marker)
hero_marker = max(PHOTO_MARKERS, key=lambda m: m.get("srtm_ele", m.get("ele", 0)))
hero_photo_name = Path(hero_marker["photo"]).name

# === 3. Generate TRAIL_MAP (GPS lat/lon from route_data) ===
track_points = route_data["track_points"]

# Downsample to ~300 points for map display
step = max(1, len(track_points) // 300)
trail_map_lines = []
for i in range(0, len(track_points), step):
    tp = track_points[i]
    trail_map_lines.append(f"[{tp['lat']},{tp['lon']}]")
# Ensure last point
if len(track_points) - 1 != (len(trail_map_lines) - 1) * step:
    tp = track_points[-1]
    trail_map_lines.append(f"[{tp['lat']},{tp['lon']}]")

TRAIL_MAP_JS = "[" + ",".join(trail_map_lines) + "]"
print(f"TRAIL_MAP: {len(trail_map_lines)} points")

# === 4. Generate PROFILE (cumulative distance + elevation) ===
# Downsample to ~200 points
profile_step = max(1, len(track_points) // 200)
profile_lines = []
for i in range(0, len(track_points), profile_step):
    tp = track_points[i]
    dist = round(tp["cumulative_distance_m"])
    ele = round(tp["ele"])
    profile_lines.append(f"[{dist},{ele}]")
if len(track_points) - 1 != (len(profile_lines) - 1) * profile_step:
    tp = track_points[-1]
    profile_lines.append(f"[{round(tp['cumulative_distance_m'])},{round(tp['ele'])}]")

PROFILE_JS = "[" + ",".join(profile_lines) + "]"
print(f"PROFILE: {len(profile_lines)} points")

# === 5. Compute display values ===
dist_display = f"{total_dist_km:.2f}"
gain_display = f"{elevation_gain:,}"
max_display = f"{max_elev:,}"

# Compact duration for pill display
dur_seconds = route_data["duration_seconds"]
dur_h = int(dur_seconds // 3600)
dur_m = int((dur_seconds % 3600) // 60)
dur_compact = f"{dur_h}小时{dur_m}分"  # "10小时28分"
duration = dur_compact

# Date parsing
start_time = route_data["start_time"]  # "2025-11-21T23:34:08+00:00"
# Convert UTC to local (UTC+8)
from datetime import datetime, timezone, timedelta
tzone = timezone(timedelta(hours=8))
dt_start = datetime.fromisoformat(start_time).astimezone(tzone)
date_main = dt_start.strftime("%Y.%m.%d")
date_sub = dt_start.strftime("%A").upper()

# === 6. Route name parts for postcard template ===
title_tag = get_in(postcard_constraints, ["copy_strategy", "title_tag"], source_constraints.get("place_name", content.get("place_name", "徒步路线")))
title_main = get_in(postcard_constraints, ["copy_strategy", "title_main"], route_name)
title_en = get_in(postcard_constraints, ["copy_strategy", "title_en"], f"{route_name} ARCHIVE".upper())

# === 7. Route notes text for back ===
story_text = (
    f"全程<strong>{dist_display}公里</strong>，"
    f"爬升<strong>{gain_display}米</strong>，"
    f"最高<strong>{max_display}米</strong>，"
    f"耗时<strong>{duration}</strong>。"
)


def build_film_ticket_html() -> str:
    """Build a structurally different postcard for the film-ticket variant."""
    front_bg = postcard_palette.get("front_bg", "#17110d")
    front_text = postcard_palette.get("front_text", "#fff4dd")
    stamp = postcard_palette.get("stamp", "#f0a33a")
    back_bg = postcard_palette.get("back_bg", "#efe1c8")
    back_ink = postcard_palette.get("back_ink", "#2b1d13")
    route_light = postcard_palette.get("route_line_light", "#fff1cb")
    route_dark = postcard_palette.get("route_line_dark", "#21160f")
    dist_max = max(1, round(track_points[-1]["cumulative_distance_m"]))
    elev_values = [round(float(tp["ele"])) for tp in track_points]
    elev_min = min(elev_values)
    elev_max = max(elev_values)
    back_story = get_in(
        postcard_constraints,
        ["copy_strategy", "back_story"],
        content.get("hike_story", "这是一段真实路线记录。"),
    )
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{route_name} · 明信片</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
:root{{
  --front-bg:{front_bg};
  --front-text:{front_text};
  --stamp:{stamp};
  --back-bg:{back_bg};
  --back-ink:{back_ink};
  --route-light:{route_light};
  --route-dark:{route_dark};
}}
body{{
  font-family:"Microsoft YaHei","PingFang SC","Noto Sans CJK SC","Noto Sans SC","Source Han Sans SC","Hiragino Sans GB",SimHei,sans-serif;
  background:#120d09;
  padding:40px;
  display:flex;
  flex-direction:column;
  gap:40px;
  align-items:center;
}}
.ticket{{
  width:1200px;
  height:800px;
  position:relative;
  overflow:hidden;
  background:var(--front-bg);
  color:var(--front-text);
  box-shadow:0 24px 80px rgba(0,0,0,.34);
}}
.front .hero{{
  position:absolute;
  inset:0 260px 0 0;
  background:url('photos/{hero_photo_name}') center/cover no-repeat;
  filter:saturate(.78) contrast(1.18);
}}
.front .hero::after{{
  content:'';
  position:absolute;
  inset:0;
  background:
    linear-gradient(90deg,rgba(18,13,9,.92) 0%,rgba(18,13,9,.66) 32%,rgba(18,13,9,.08) 70%),
    radial-gradient(circle at 62% 24%,rgba(240,163,58,.16),transparent 30%);
}}
.film-rail{{
  position:absolute;
  left:0;
  right:260px;
  height:36px;
  z-index:6;
  background:repeating-linear-gradient(90deg,var(--stamp) 0 18px,transparent 18px 34px);
  opacity:.95;
}}
.film-rail.top{{top:22px}}
.film-rail.bottom{{bottom:22px}}
.title-block{{
  position:absolute;
  left:70px;
  top:120px;
  width:560px;
  z-index:8;
}}
.place-pill{{
  display:inline-flex;
  border:2px solid var(--stamp);
  color:var(--stamp);
  border-radius:999px;
  padding:8px 18px;
  font-size:17px;
  font-weight:950;
  margin-bottom:24px;
}}
.route-name{{
  font-size:106px;
  font-weight:950;
  line-height:.96;
  letter-spacing:0;
  color:var(--front-text);
  text-shadow:10px 10px 0 rgba(240,163,58,.16);
  text-wrap:balance;
}}
.archive{{
  margin-top:18px;
  color:var(--stamp);
  font-size:14px;
  font-weight:950;
  letter-spacing:5px;
}}
.ticket-stub{{
  position:absolute;
  top:0;
  right:0;
  width:260px;
  height:100%;
  z-index:9;
  background:
    radial-gradient(circle at 0 28px,transparent 0 14px,var(--stamp) 15px),
    linear-gradient(180deg,#f2a63b,#d97929);
  color:#1d120b;
  border-left:3px dashed rgba(29,18,11,.72);
  padding:42px 28px;
  display:flex;
  flex-direction:column;
  justify-content:space-between;
}}
.stub-kicker{{
  writing-mode:vertical-rl;
  text-orientation:mixed;
  align-self:flex-end;
  font-size:18px;
  font-weight:950;
  letter-spacing:4px;
}}
.date{{
  font-size:36px;
  line-height:1.05;
  font-weight:950;
  letter-spacing:2px;
}}
.date small{{
  display:block;
  margin-top:6px;
  font-size:11px;
  letter-spacing:5px;
  color:rgba(29,18,11,.66);
}}
.stub-data{{
  display:grid;
  gap:12px;
}}
.stub-data div{{
  border-top:2px solid rgba(29,18,11,.42);
  padding-top:10px;
}}
.stub-data span{{
  display:block;
  font-size:11px;
  font-weight:950;
  color:rgba(29,18,11,.58);
}}
.stub-data b{{
  display:block;
  margin-top:2px;
  font-size:27px;
  line-height:1;
  font-weight:950;
}}
.map-window{{
  position:absolute;
  left:72px;
  bottom:82px;
  width:520px;
  height:260px;
  z-index:8;
  border:2px dashed rgba(240,163,58,.72);
  background:rgba(18,13,9,.38);
  box-shadow:0 18px 50px rgba(0,0,0,.26);
}}
.map-window canvas{{
  width:100%;
  height:100%;
  display:block;
}}
.team-watermark{{
  position:absolute;
  left:70px;
  bottom:44px;
  z-index:8;
  font-size:12px;
  font-weight:900;
  letter-spacing:3px;
  color:rgba(255,244,221,.44);
}}
.back{{
  background:var(--back-bg);
  color:var(--back-ink);
  display:grid;
  grid-template-columns:430px 1fr;
}}
.back::before{{
  content:'';
  position:absolute;
  inset:0;
  pointer-events:none;
  background:
    radial-gradient(circle at 12% 20%,rgba(43,29,19,.08),transparent 22%),
    linear-gradient(rgba(43,29,19,.045) 1px,transparent 1px),
    linear-gradient(90deg,rgba(43,29,19,.035) 1px,transparent 1px);
  background-size:auto,32px 32px,32px 32px;
}}
.back-left{{
  padding:54px 42px;
  border-right:3px dashed rgba(43,29,19,.54);
  position:relative;
  z-index:2;
}}
.back-left h2{{
  font-size:46px;
  line-height:1.05;
  letter-spacing:0;
}}
.back-left p{{
  margin-top:20px;
  font-size:16px;
  line-height:1.85;
}}
.elevation-chart{{
  margin-top:30px;
  height:190px;
  border:2px solid rgba(43,29,19,.64);
}}
.elevation-chart canvas{{width:100%;height:100%}}
.back-right{{
  position:relative;
  z-index:2;
  padding:54px 56px;
}}
.stamp-box{{
  position:absolute;
  top:54px;
  right:56px;
  width:132px;
  height:152px;
  border:3px dashed var(--stamp);
  display:grid;
  place-items:center;
  color:var(--stamp);
  font-weight:950;
}}
.message{{
  position:absolute;
  left:56px;
  right:56px;
  bottom:72px;
  display:grid;
  gap:22px;
}}
.message div{{
  height:24px;
  border-bottom:2px solid rgba(43,29,19,.45);
}}
</style>
</head>
<body>
<section class="ticket front">
  <div class="hero"></div>
  <div class="film-rail top"></div>
  <div class="film-rail bottom"></div>
  <div class="title-block">
    <div class="place-pill">{title_tag}</div>
    <div class="route-name">{route_name}</div>
    <div class="archive">{title_en}</div>
  </div>
  <div class="map-window"><canvas id="frontCanvas"></canvas></div>
  <div class="team-watermark">{team_name.upper()} / FIELD TICKET</div>
  <aside class="ticket-stub">
    <div class="stub-kicker">HARD ROUTE</div>
    <div class="date">{date_main}<small>{date_sub}</small></div>
    <div class="stub-data">
      <div><span>KM</span><b>{dist_display}</b></div>
      <div><span>UP</span><b>{gain_display}M</b></div>
      <div><span>TIME</span><b>{duration}</b></div>
      <div><span>MAX</span><b>{max_display}M</b></div>
    </div>
  </aside>
</section>
<section class="ticket back">
  <div class="back-left">
    <h2>{route_name}</h2>
    <p>{back_story}</p>
    <div class="elevation-chart"><canvas id="backElevation"></canvas></div>
  </div>
  <div class="back-right">
    <div class="stamp-box">STAMP</div>
    <div class="message">
      <div></div><div></div><div></div><div></div><div></div><div></div><div></div>
    </div>
  </div>
</section>
<script>
const TRAIL_MAP={TRAIL_MAP_JS};
const PROFILE={PROFILE_JS};
const DIST_MAX={dist_max};
const ELEV_MIN={elev_min};
const ELEV_MAX={elev_max};

(function(){{
  const c=document.getElementById('frontCanvas');
  const ctx=c.getContext('2d');
  const W=520,H=260,dpr=2;
  c.width=W*dpr;c.height=H*dpr;ctx.scale(dpr,dpr);
  const pad=28,pw=W-pad*2,ph=H-pad*2;
  let minLat=90,maxLat=-90,minLon=180,maxLon=-180;
  TRAIL_MAP.forEach(p=>{{minLat=Math.min(minLat,p[0]);maxLat=Math.max(maxLat,p[0]);minLon=Math.min(minLon,p[1]);maxLon=Math.max(maxLon,p[1]);}});
  const latR=maxLat-minLat||1,lonR=maxLon-minLon||1;
  const mapX=lon=>pad+((lon-minLon)/lonR)*pw;
  const mapY=lat=>pad+ph-((lat-minLat)/latR)*ph;
  ctx.strokeStyle='rgba(255,241,203,.46)';ctx.lineWidth=1;
  for(let i=0;i<9;i++){{const x=pad+i*pw/8;ctx.beginPath();ctx.moveTo(x,pad);ctx.lineTo(x,pad+ph);ctx.stroke();}}
  for(let i=0;i<5;i++){{const y=pad+i*ph/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(pad+pw,y);ctx.stroke();}}
  function draw(style,width){{ctx.beginPath();TRAIL_MAP.forEach((p,i)=>{{const x=mapX(p[1]),y=mapY(p[0]);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}});ctx.strokeStyle=style;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}}
  draw('rgba(18,13,9,.76)',9);draw('rgba(255,241,203,.96)',4);
  [0,TRAIL_MAP.length-1].forEach((idx,i)=>{{const p=TRAIL_MAP[idx],x=mapX(p[1]),y=mapY(p[0]);ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fillStyle=i?'#f0a33a':'#fff1cb';ctx.fill();ctx.strokeStyle='#21160f';ctx.lineWidth=2;ctx.stroke();}});
}})();

(function(){{
  const c=document.getElementById('backElevation');
  const ctx=c.getContext('2d');
  const rect=c.parentElement.getBoundingClientRect();
  const W=rect.width,H=rect.height,dpr=2;
  c.width=W*dpr;c.height=H*dpr;ctx.scale(dpr,dpr);
  const pad={{t:18,r:18,b:24,l:24}},cw=W-pad.l-pad.r,ch=H-pad.t-pad.b;
  ctx.beginPath();ctx.moveTo(pad.l,H-pad.b);
  PROFILE.forEach(pt=>{{const x=pad.l+(pt[0]/DIST_MAX)*cw;const y=pad.t+ch-((pt[1]-ELEV_MIN)/(ELEV_MAX-ELEV_MIN||1))*ch;ctx.lineTo(x,y);}});
  ctx.lineTo(W-pad.r,H-pad.b);ctx.closePath();ctx.fillStyle='rgba(240,163,58,.13)';ctx.fill();
  ctx.beginPath();
  PROFILE.forEach((pt,i)=>{{const x=pad.l+(pt[0]/DIST_MAX)*cw;const y=pad.t+ch-((pt[1]-ELEV_MIN)/(ELEV_MAX-ELEV_MIN||1))*ch;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}});
  ctx.strokeStyle='#2b1d13';ctx.lineWidth=2.2;ctx.stroke();
}})();
</script>
</body>
</html>
"""


if style_variant == "film_ticket":
    OUTPUT.mkdir(parents=True, exist_ok=True)
    output_path = OUTPUT / "trail_postcard.html"
    html = build_film_ticket_html()
    output_path.write_text(html, encoding="utf-8")
    print(f"\nWritten {len(html):,} bytes to {output_path}")
    print(f"Design constraints: postcard style_variant='{style_variant}', title='{title_main}'")
    print("BUILD POSTCARD COMPLETE")
    sys.exit(0)

# === 8. Read postcard template ===
template_path = BASE_DIR / "assets/templates/trail_postcard.html"
with open(template_path, "r", encoding="utf-8") as f:
    template = f.read()

palette_defaults = {
    "--front-bg": postcard_palette.get("front_bg", "#0f1117"),
    "--front-text": postcard_palette.get("front_text", "#f5f0e8"),
    "--stamp": postcard_palette.get("stamp", "#d6a84f"),
    "--back-bg": postcard_palette.get("back_bg", "#f4efe4"),
    "--back-ink": postcard_palette.get("back_ink", "#273128"),
    "--route-light": postcard_palette.get("route_line_light", "#fff8e5"),
    "--route-dark": postcard_palette.get("route_line_dark", "#171b14"),
}
palette_css = "".join(f"{key}:{value};" for key, value in palette_defaults.items())
if style_variant == "film_ticket":
    palette_css += (
        "--variant-bg-noise:rgba(255,244,221,0.06);"
        "--variant-photo-width:570px;"
        "--variant-photo-height:610px;"
        "--variant-photo-right:70px;"
        "--variant-photo-top:72px;"
        "--variant-photo-clip:polygon(0 0,100% 0,100% 100%,0 100%);"
        "--variant-title-size:82px;"
        "--variant-title-width:520px;"
        "--variant-stat-bottom:92px;"
        "--variant-stat-width:500px;"
    )
else:
    palette_css += (
        "--variant-bg-noise:rgba(232,223,211,0.045);"
        "--variant-photo-width:650px;"
        "--variant-photo-height:610px;"
        "--variant-photo-right:48px;"
        "--variant-photo-top:70px;"
        "--variant-photo-clip:polygon(10% 0,100% 0,90% 100%,0 100%);"
        "--variant-title-size:96px;"
        "--variant-title-width:430px;"
        "--variant-stat-bottom:104px;"
        "--variant-stat-width:430px;"
    )
template = template.replace(
    ":root{--pine:#6d8b5e;--mineral:#5a7a6a;--earth-gold:#c4a87a;--warm-sand:#e8dfd3;--dark:#1a1a1a;--cream:#f5f0e8;--accent:#e07b3c}",
    ":root{--pine:#6d8b5e;--mineral:#5a7a6a;--earth-gold:#c4a87a;--warm-sand:#e8dfd3;--dark:#1a1a1a;--cream:#f5f0e8;--accent:#e07b3c;" + palette_css + "}",
)
template = template.replace("background:#10120f;color:var(--cream)", "background:var(--front-bg);color:var(--front-text)")
template = template.replace("background:#10120f;padding:40px", "background:var(--front-bg);padding:40px")
template = template.replace("background:var(--cream);display:flex", "background:var(--back-bg);display:flex")
template = template.replace("color:#181a14", "color:var(--back-ink)")
template = template.replace("background:var(--earth-gold)", "background:var(--stamp)")
template = template.replace("color:var(--earth-gold)", "color:var(--stamp)")

variant_css = """
body.variant-trail-permit-pass .front .bg-photo{right:var(--variant-photo-right);top:var(--variant-photo-top);width:var(--variant-photo-width);height:var(--variant-photo-height);clip-path:var(--variant-photo-clip)}
body.variant-trail-permit-pass .front .title-main{font-size:var(--variant-title-size)}
body.variant-trail-permit-pass .front .stats-row{bottom:var(--variant-stat-bottom);width:var(--variant-stat-width)}
"""
if style_variant == "film_ticket":
    variant_css = """
body.variant-film-ticket .front::before{background:radial-gradient(circle at 18% 24%,rgba(240,163,58,.13),transparent 26%),linear-gradient(var(--variant-bg-noise) 1px,transparent 1px),linear-gradient(90deg,var(--variant-bg-noise) 1px,transparent 1px);background-size:auto,28px 28px,28px 28px}
body.variant-film-ticket .front .bg-photo{right:var(--variant-photo-right);top:var(--variant-photo-top);width:var(--variant-photo-width);height:var(--variant-photo-height);clip-path:var(--variant-photo-clip);border:0;filter:saturate(.78) contrast(1.16)}
body.variant-film-ticket .front .bg-photo::before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.34),transparent 18%,transparent 82%,rgba(0,0,0,.34));z-index:2}
body.variant-film-ticket .front .vignette{background:linear-gradient(90deg,rgba(23,17,13,1) 0%,rgba(23,17,13,.88) 39%,rgba(23,17,13,.18) 100%)}
body.variant-film-ticket .front .top-strip{height:22px;background:repeating-linear-gradient(90deg,var(--stamp) 0 22px,transparent 22px 34px)}
body.variant-film-ticket .front .title-block{top:118px;width:var(--variant-title-width)}
body.variant-film-ticket .front .title-tag{border:2px solid var(--stamp);background:transparent;color:var(--stamp);padding:8px 16px;border-radius:999px}
body.variant-film-ticket .front .title-main{font-size:var(--variant-title-size);color:var(--front-text);text-shadow:8px 8px 0 rgba(240,163,58,.18)}
body.variant-film-ticket .front .title-en{color:var(--stamp);letter-spacing:4px}
body.variant-film-ticket .front .stats-row{bottom:var(--variant-stat-bottom);width:var(--variant-stat-width);border:2px dashed rgba(240,163,58,.72);background:rgba(255,244,221,.08)}
body.variant-film-ticket .front .stat-pill{background:rgba(255,244,221,.07)}
body.variant-film-ticket .front .trail-canvas{right:88px;bottom:72px;width:260px;height:200px}
body.variant-film-ticket .front .tape{display:none}
body.variant-film-ticket .back{background:var(--back-bg)}
body.variant-film-ticket .back::before{background:radial-gradient(circle at 15% 20%,rgba(43,29,19,.08),transparent 22%),linear-gradient(rgba(43,29,19,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(43,29,19,.035) 1px,transparent 1px);background-size:auto,32px 32px,32px 32px}
body.variant-film-ticket .back .stamp-box{border-style:dashed;border-color:var(--stamp);color:var(--stamp);transform:rotate(4deg)}
body.variant-film-ticket .back .graffiti-box{background:rgba(240,163,58,.08);border-style:dashed}
"""
template = template.replace("</style>", variant_css + "\n</style>")

# === 9. Replace data in template ===
# Replace TRAIL_MAP
tm_pattern = r'const TRAIL_MAP=\[\[[\d.,\[\]]+\];'
tm_replacement = f'const TRAIL_MAP={TRAIL_MAP_JS};'
# Need to match the full array - it's a very long line
# Use regex to find and replace
tm_match = re.search(r'const TRAIL_MAP=\[\[.*?\];', template, re.DOTALL)
if tm_match:
    template = template[:tm_match.start()] + tm_replacement + template[tm_match.end():]
    print("TRAIL_MAP replaced")

# Replace PROFILE
pf_match = re.search(r'const PROFILE=\[\[.*?\];', template, re.DOTALL)
if pf_match:
    pf_replacement = f'const PROFILE={PROFILE_JS};'
    template = template[:pf_match.start()] + pf_replacement + template[pf_match.end():]
    print("PROFILE replaced")

# Replace stats in HTML
replacements = [
    ('［路线名称］', route_name),
    ('［地点］', title_tag),
    ('［日期］', date_main),
    ('［星期］', date_sub),
    ('TRAIL ARCHIVE', title_en),
    ('photos/hero.jpg', f'photos/{hero_photo_name}'),
    ('0.00', dist_display),
    ('<span class="val">0</span><span class="lbl">爬升 M ↑</span>', f'<span class="val">{gain_display}</span><span class="lbl">爬升 M ↑</span>'),
    ('<span class="val">0</span><span class="lbl">最高 M ▲</span>', f'<span class="val">{max_display}</span><span class="lbl">最高 M ▲</span>'),
    ('0分钟', duration),
    ('全程<strong>0.00公里</strong>', f'全程<strong>{dist_display}公里</strong>'),
    ('爬升<strong>0米</strong>', f'爬升<strong>{gain_display}米</strong>'),
    ('最高<strong>0米</strong>', f'最高<strong>{max_display}米</strong>'),
    ('耗时<strong>0分钟</strong>', f'耗时<strong>{duration}</strong>'),
]

for old, new in replacements:
    template = template.replace(old, new)
    print(f"  Replaced '{old}' → '{new}'")

story_new = get_in(postcard_constraints, ["copy_strategy", "back_story"], (
    content.get("hike_story", "这是一段真实路线记录。")
))
summary_match = re.search(r'<div class="summary-text">\s*全程<strong>.*?</div>', template, re.DOTALL)
if summary_match:
    summary_html = (
        '<div class="summary-text">\n'
        f'        {story_text}\n'
        '      </div>'
    )
    template = template[:summary_match.start()] + summary_html + template[summary_match.end():]

template = template.replace('［团队名称］', team_name)
template = template.replace('SHANYE LUJI', team_name.upper())
body_class = "variant-film-ticket" if style_variant == "film_ticket" else "variant-trail-permit-pass"
template = template.replace("<body>", f'<body class="{body_class}">')

# === 10. Write output ===
OUTPUT.mkdir(parents=True, exist_ok=True)
output_path = OUTPUT / "trail_postcard.html"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(template)

print(f"\nWritten {len(template):,} bytes to {output_path}")
print(f"Design constraints: postcard title='{title_main}', subtitle='{title_en}'")
print("BUILD POSTCARD COMPLETE")
